name: Deploy to S3

on:
  push:
    branches:
      - start-ad-stop-lambda 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Secrets
      run: |
        echo "AWS_ACCESS_KEY_ID exists: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
        echo "AWS_SECRET_ACCESS_KEY exists: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your AWS region

    - name: Upload HTML to S3
      run: |
        aws s3 cp index.html s3://verblaze.tlvtech.io/index.html --acl public-read
